#!/usr/bin/env zsh

current_session=$(tmux display-message -p '#{session_name}')

if [[ "$current_session" == "scratch" ]]; then
  tmux switch-client -l
  exit 0
fi

if ! tmux has-session -t '=scratch' 2>/dev/null; then
  current_path=$(tmux display-message -p '#{pane_current_path}')
  tmux new-session -d -s scratch -n scratch -c "$current_path"
fi

tmux switch-client -t '=scratch'
